# Generated by Django 2.2.5 on 2019-12-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0004_auto_20191219_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
