# Generated by Django 2.2.5 on 2019-12-20 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0005_auto_20191219_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_creator_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
